id: IC43FFAC9
legacy_id: P004200
ocr_import_info:
  bdrc_scan_id: W00KG03792
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T05:46:33'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T12:10:57.620391+00:00'
last_modified: 2022-08-29 20:11:12.159474
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00KG03792
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW00KG03792
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དངུལ་ཆུ་བཙོ་བཀྲུ་ཆེན་མོ་ཇི་ལྟར་བསྒྲུབས་པའི་རྟོགས་བརྗོད།
  author: བསྟན་འཛིན་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.9473101429423141
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I00KG03822:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03822
      total_pages: 90
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG03822.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9473101429423141
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
